sequencesender/sequencesender.go, sequencesender/sequencesender_test.go, sequencesender/txbuilder/banana_base.go, sequencesender/txbuilder/banana_base_test.go, sequencesender/txbuilder/banana_types.go
When a sequence is build it checks that the L1InfoTreeCount set include the indexes inside batchL2data of all batches conforming the sequence
=> feat: seq sender sanity check l1infotree

test/access-list-e2e.bats, test/basic-e2e.bats, test/bridge-e2e.bats, test/helpers/common-setup.bash, test/helpers/common.bash, test/helpers/lxly-bridge-test.bash, test/scripts/env.sh, test/scripts/kurtosis_prepare_params_yml.sh
This PR introduces custom native gas token transfer for CDK chain e2e test. The custom native gas token on CDK is originating from the L1 network and is mapped to some existing L1 ERC20 token. Test checks whether native token balance of receiver account increases by the deposited amount on the L2.
The use case is described [here](https://github.com/0xPolygon/kurtosis-cdk/blob/main/docs/native-token/native-token.md).
=> test: Custom native gas token transfer E2E test

.github/workflows/test-e2e.yml
This will ensure ci is deterministic while using the same version.
=> ci: pin kurtosis-cdk version in tests

go.mod, go.sum
-  update zkevm-synchronizer-l1 from [v1.0.1](https://github.com/0xPolygonHermez/zkevm-synchronizer-l1/releases/tag/v1.0.1) to [v1.0.2](https://github.com/0xPolygonHermez/zkevm-synchronizer-l1/releases/tag/v1.0.2): 
- fix: [#119](https://github.com/0xPolygonHermez/zkevm-synchronizer-l1/issues/119), fails if there are multiple sequencedBatch in same bock because a SQL have wrong order by  (#120)
- feat: add check to DB configuration (#118)
- fix: downgrade migrations sql lite, remove scheme prefix from tables names (#117)
=> fix: aggregator sync multi seqbatches same block

scripts/local_config, scripts/run_template.go, test/config/kurtosis-cdk-node-config.toml.template
Last changes on `kurtosis-cdk` main brach have changed the way that kurtosis answer to ports and also have change some end-points names. 
- Some request of ports return the protocol and another no so the code have been updated to support port with protocol or without (`http://127.0.0.1:8023` or `127.0.0.1:8023`) 
- Also, to support changing end-point names have include a list of 'end-points' to get the URL / port
- There was a hardcoded path in config file that have been changed by vars and left the absolute path used by kurtosis as deault value
=> feat: adapt kurtosis cdk and fix errors

.github/workflows/release.yml
Allow release from flexible tags
=> ci: fix release tags

crates/cdk-config/src/aggregator.rs, crates/cdk-config/src/sequence_sender.rs
This is necessary because we're not going to check for any values at this point.
=> refactor: accept empty config file

Cargo.lock, crates/cdk/Cargo.toml, crates/cdk/src/cli.rs, crates/cdk/src/helpers.rs, crates/cdk/src/main.rs, crates/cdk/src/versions.rs
This PR splits the previously global required config and genesis flags to different subcommands as not all commands need the same params.
`node` command is getting the node config file
`erigon` command is getting the config file and the genesis file
`versions` command doesn't need any param
Introducing here the `versions` command, simply outputs the corresponding versions of other components. This is a temporary launch requirement until we iterate on more comprehensive status checks.
=> feat: add versions command

crates/cdk/src/cli.rs, test/combinations/fork11-rollup.yml, test/combinations/fork12-cdk-validium.yml, test/combinations/fork12-rollup.yml, test/combinations/fork9-cdk-validium.yml
There was a conflict with a the config shorthand, renamed to '-C'
* Added descriptions to commands.
* Bump cdk-erigon
=> fix: shorthand and add descriptions

l1infotree/tree.go, l1infotree/tree_test.go
Revert changes on l1infotree/tree.go calculating merkel proof. This object is used by aggregator
=> fix: revert changes on calculation of merkel proof

go.mod, go.sum
=> chore: update zkevm-ethtx-manager to v0.2.1 (#153)

aggsender/aggsender.go, aggsender/db/aggsender_db_storage_test.go, aggsender/db/migrations/0001.sql, aggsender/types/types.go
This PR adds three new fields to the `CertificateInfo` struct we save in `aggsender` `db`:
- `created_at` - a timestamp that indicates when was the certificate created on the `aggsender`.
- `updated_at` - a timestamp that indicates when was the certificate last updated. For example, it moved from Pending to Candidate.
- `signed_cerificated` - raw string of the certificate that we sent to `agglayer`.
All of these fields will be used for easier debugging and logging.
=> feat: add timestamps to certificate

.github/workflows/test-e2e.yml, scripts/local_config, test/combinations/fork11-rollup.yml, test/combinations/fork12-cdk-validium.yml, test/config/kurtosis-cdk-node-config.toml.template
- It set the config param `PathRWData` to a variable that can be set depending of local run or kurtosis:
-  Executing `script/local_config` writes all data on `./tmp/cdk/runtime/` 
- Fix the parameters required by kurtosis to run
=> fix:  local configuration bumping kurtosis to 0.2.29

sequencesender/txbuilder/banana_base.go, sequencesender/txbuilder/banana_base_test.go
=> feat: remove sanity check

bridgesync/e2e_test.go, crates/cdk/versions.json, go.mod, go.sum, l1infotreesync/downloader_test.go, l1infotreesync/e2e_test.go, l1infotreesync/l1infotreesync.go, l1infotreesync/processor.go, lastgersync/e2e_test.go, reorgdetector/types.go, sync/evmdownloader.go, test/helpers/wait.go
Fix l1 info tree flacky test. PoW:
=> fix: l1infotree flaky test

cmd/run.go, common/components.go
Cherry pick ssender sync only on branch 0.4.0 to be using during Cardona update preparation.
=> feat: l1infotreesync can be run as individual component (#188)

aggregator/aggregator.go, aggregator/aggregator_test.go
Cleans proof table on aggregator start to ensure all the acc input hash is properly calculated for all pending batches.
Fixes #201
=> fix: clean proof table on start

.github/workflows/test-e2e.yml, .github/workflows/test-resequence.yml
Rather than building the `cdk` image in each test job, create it in an initial job and reuse that built image for all subsequent test jobs.
It also bumps to the latest kurtosis-cdk version.
E2E tests pass on my fork: https://github.com/leovct/cdk/actions/runs/12069227043
=> ci: build cdk image once for all e2e test jobs

agglayer/types.go, agglayer/types_test.go, aggsender/aggsender.go, aggsender/types/types.go, db/meddler.go, go.mod
This PR simplifies the `HashMeddler` logic a bit, because it supports both nullable and non-nullable fields. Also, fix some logs and minor stuff.
=> chore: simplify the `HashMeddler`

aggsender/aggsender.go, aggsender/aggsender_test.go
The PR returns an error in case agglayer returns lower height for the last certificate than the one found in the aggsender's local storage.
=> feat: report error in case agglayer returns lower height than in storage

.github/workflows/test-e2e.yml, .github/workflows/test-resequence.yml, aggsender/aggsender.go, aggsender/aggsender_test.go, aggsender/config.go, aggsender/db/aggsender_db_storage.go, aggsender/db/aggsender_db_storage_test.go, aggsender/db/migrations/0001.sql, aggsender/db/migrations/migrations.go, aggsender/types/types.go, config/default.go, db/migrations.go, test/combinations/fork11-rollup.yml, test/combinations/fork12-cdk-validium.yml, test/combinations/fork12-pessimistic.yml, test/combinations/fork12-rollup.yml, test/combinations/fork9-cdk-validium.yml
- Add new field `retries` to database, that keep the count of times of regenerated the certificate
- The discarded certificates are move (if configuration allow that) to a new table `certificate_info_history`
- Cherry-picked #202 to fix e2e-test
```
[AggSender]
KeepCertificatesHistory = true
```
- Define the retain policy
=> feat: write on database the number of retries per certificate and the certificates in a history table

aggsender/aggsender_test.go, aggsender/config.go, config/default.go, test/config/kurtosis-cdk-node-config.toml.template
This PR removes deprecated config fields from the `aggsender`'s config:
- `BlockGetInterval`
- `CheckSettledInterval`
=> fix: remove deprecated `aggsender` config fields

aggsender/aggsender.go, aggsender/aggsender_test.go, aggsender/config.go, aggsender/types/certificate_build_params.go, config/default.go
Cherry pick PR #217  and PR #209 from `release/v0.5.0`
=> feat:  cherry pick pr 217 and 209 from `release/v0.5.0`
