.github/workflows/test-resequence.yml
Update code to dynamically fetch polycli version for resequence test
=> ci: fetch polycli version from environment

.github/workflows/release.yml
=> chore: Change release regex check

.github/workflows/release.yml
=> Revert "chore: Change release regex check"

go.mod, go.sum
=> feat: Upgraded cdk-rpc dep version

cmd/run.go, config/default.go
Checks RPCURL is set on sequence sender config
=> fix: check ssender config

go.mod, go.sum
Check: [zkevm-synchronizer-l1 issue 127](https://github.com/0xPolygonHermez/zkevm-synchronizer-l1/issues/127) 
If this error appears means that is very likely that the genesisBlock used is wrong.
A possible way to fix that is: 
- Set to auto-discover genensis Block: 
```
[Aggregator.Synchronizer.Synchronizer]
GenesisBlockNumber = 0
```
````
zkevm10-node  | 2024-10-07T15:04:38.400Z        WARN    banana/processor_update_l1_info_tree_v2.go:58   this l1nfotree is not stored on local DB. So can't check it: data:CurrentL1InfoRoot: 0x27af58b07631bf815fb61402f5c3dabf5db30f7eec61347892ac7793cb1614db LeafCount: 3791 BlockHash: 0x0000000000000000000000000000000000000000000000000000000000000000 MinTimestamp: 1726547352       {"pid": 7}
zkevm10-node  | …
```
=> fix: cdk-525, if sanity check of  l1infotreeupdatev2 fails, is an error and need to stop syncing

crates/cdk-config/src/aggregator.rs, crates/cdk-config/src/l1.rs, crates/cdk-config/src/lib.rs, crates/cdk-config/src/network_config.rs
=> refactor: set default on all config values

l1infotreesync/e2e_test.go, l1infotreesync/processor.go, l1infotreesync/processor_test.go, sync/evmdriver.go
- Added syncer restart to the e2e tests
- Added more unit tests to the processor
=> feat: L1 Info Tree sync testing

sequencesender/ethtx.go, sequencesender/sequencesender.go, sequencesender/sequencesender_test.go
The PR includes handling of context, some simplifications (extracting common parts of the code to functions), and relying on tickers instead of `time.Sleep`.
=> chore: sequence sender improvements

aggregator/aggregator_test.go
=> test: aggregator

aggregator/aggregator.go
Adds sanity check when a batch start is received from the DS in the aggregator.
=> feat: currentStreamBatchRaw sanity check

aggregator/aggregator.go
=> feat: currentStreamBatchRaw sanity check (#131)

db/meddler.go, db/sqlite.go, l1infotreesync/e2e_test.go, sync/evmdriver.go
Fixing L1 info tree sync tests
=> fix: Fixing L1 info tree sync tests

go.mod, go.sum
Updates DS lib to the latest version.
=> feat: update ds lib

db/meddler.go, db/sqlite.go, l1infotreesync/e2e_test.go, sync/evmdriver.go
* fix: Fix l1infotreesync tests
Cherry picks #130
=> fix: Fixing L1 info tree sync tests (#130)

.github/workflows/test-e2e.yml, scripts/local_config, test/bridge-e2e.bats, test/combinations/fork11-rollup.yml, test/combinations/fork12-cdk-validium.yml, test/combinations/fork12-rollup.yml, test/combinations/fork9-cdk-validium.yml, test/helpers/common-setup.bash, test/helpers/common.bash, test/helpers/lxly-bridge-test.bash, test/run-e2e.sh, test/scripts/batch_verification_monitor.sh, test/scripts/env.sh
Also bump necessary versions in combinations.
=> ci: bump kurtosis version

.github/workflows/lint-pr.yml
Do not check individual commits linting in PRs
=> ci: remove commit linting

go.mod, go.sum
update zkevm-ethtx-manager to v0.2.1
=> feat: update zkevm-ethtx-manager to v0.2.1

aggregator/aggregator.go, aggregator/aggregator_test.go, scripts/local_config
Fixes local acc input has calculation
=> fix: acc input hash calculation

dataavailability/datacommittee/datacommittee.go
Extension of [PR-152](https://github.com/0xPolygon/cdk/pull/152) that refactors the `GetSequence` method
=> refactor: GetSequence

aggregator/aggregator.go, aggregator/aggregator_test.go
* fix: clean proof table on start
Cherry picks #207
=> fix: clean proof table on start (#207)

.github/workflows/test-e2e.yml, .github/workflows/test-resequence.yml, aggsender/aggsender.go, aggsender/aggsender_test.go, aggsender/config.go, aggsender/db/aggsender_db_storage.go, aggsender/db/aggsender_db_storage_test.go, aggsender/db/migrations/0001.sql, aggsender/db/migrations/migrations.go, aggsender/types/types.go, config/default.go, db/migrations.go, test/combinations/fork11-rollup.yml, test/combinations/fork12-cdk-validium.yml, test/combinations/fork12-pessimistic.yml, test/combinations/fork12-rollup.yml, test/combinations/fork9-cdk-validium.yml
=> feat: cherry-pick PR #208 from release/v0.5.0

aggsender/aggsender_test.go, aggsender/config.go, config/default.go, test/config/kurtosis-cdk-node-config.toml.template
This PR cherry picks [PR 222](https://github.com/0xPolygon/cdk/pull/222) to release v0.5.0 branch.
=> fix: cherry pick of PR-222 to release branch
